name: Flow
on:
  push:
    branches:
      - 'main'
jobs:
  release-on-merge:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions: write-all
    # needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # actions by github to checkout repository
        with:
          fetch-depth: 0
      - name: Cache npm
        uses: actions/cache@v3
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Derive appropriate SHAs for base and head for `nx affected`
        uses: nrwl/nx-set-shas@v3
        with:
          main-branch-name: 'main'
      - name: Npm install
        run: npm i
      - name: Build release bundle
        run: npx nx affected -t lint build
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
